### ISSUE TITLE
Suggestion: show full code in brackets on plus.codes

### ISSUE THREAD

**Issue by answerquest** [google/open-location-code#126]
Hi, sharing an issue with plus codes that say a postal service or a database operating at the level of a country like India would experience:

* I have one location in Pune city, which is in Maharashtra state of India: https://i.imgur.com/1xlxexM.png
* I copy the plus-code given at the bottom. It is a shortened version, but an unfamiliar person wouldn't know.
* I open maps.google.com and am looking at all of India. I type in the plus code : GRW4+7J . It takes me to another address in another state.
* I search for  "GRW4+7J, maharashtra". It still takes me to another address in the state.
* I include two more letters from the left of the full plus code (note, at this point the lay person will have abandoned the search): CMGRW4+7J
* I go back to all-India map, and search for it. It takes me to the ocean, somewhere near Myanmar.
* It's only when I type the full code, 7JCMGRW4+7J that I get the correct location.

Can we make arrangements so the default display on plus.codes (that shows at the bottom of the page) shows the full code in small size in brackets to the right or something, or in a ?-tooltip advising the user to use the full code in case of searching over a large area like state or country? It's there when you click further, but it's not very intuitive to open that and doesn't always open. 

Also, a copy-to-clipboard button would be great!

**Comment by bocops** [comment]
Hi @answerquest 

The idea is to use a regional landmark or other useful location information in combination with short codes. For example, if I search on Google Maps for "GRW4+7J Pashan", the result is the correct location.

I agree that this could be made more obvious on plus.codes, but I guess that this web page is still meant for those already being aware of how OLC works. A button to copy to clipboard would be great, yes.

**Comment by drinckes** [comment]
Hi - think of the plus code as similar to a street name and number. You wouldn't expect to tell someone in another state that your entire address was "11 X Road" - but you'd include the town as well. Similarly, telling me the address is "GRW4+7J, maharashtra" isn't super helpful, that's why it displays the locality "Pashan, Pune". 

I don't think showing the full code is the solution - we want to make these easier to use, so we show a short version of the code with the town or locality name.

If you have any suggestion how to make it more obvious that they go together, let me know!

(I'll look into a copy to clipboard button.)

**Comment by bocops** [comment]
@drinckes This is probably more an issue with the Maps API than with OLC - but is there any way to somehow "normalize" the location that is displayed as a reference?

Clicking around the map, I often (for locations in Germany) get the short code followed by a city name and "Germany", which is what I'd expect to be most useful in most cases. Example: **PJWW+8M Trier, Germany**

Sometimes, though, I also get something that includes a zip code either as a prefix (**3Q45+JV 99958 Tonna, Germany**) or somewhere in the location string (**HP29+2Q Lauter, 08315 Lauter-Bernsbach, Germany**). At other times, I get a string that includes a mostly useless district name (like "Mitte" in **2G7R+FP Mitte, Bielefeld, Germany**).

If there was a way to select _shortest_ globally unique reference_ (which might be CITY, COUNTRY in most cases) and/or _shortest reference unique within country_ (which would probably by CITY), this could help in formatting the resulting short code plus reference location in a way that makes it more obvious that they can and should be copied together.

**Comment by rsramek** [comment]
@bocops Locations will be formatted much more compactly in future, hopefully Q1/Q2 and would be also receivable directly from Maps API.

**Comment by malleo** [comment]
Wouldn't it be usefull to to have a table with entrys for each 4 digit OLC area code which contains unambigous locality names for each country or in total?
There are 64800 area codes in total. I guess about 50% of them are pure water or ice areas with no localities at all.
So if each entry would take about 50 bytes for area code locality and country name, that table would have a total size of about 1.5 MB. Such  tables for single countrys would be much smaller and easier to maintain.

**Comment by bocops** [comment]
I feel that that would be doing things slightly backwards.

First of all, the result of that suggestion would be a string like **_226J+9X_, F5, Washington D.C.** Basically, the plus code would no longer be a single string, but separated into a 4+2 short code and two additional digits that dangle between code and name. If we want to use 6+2 digits of the full code, anyway, it would be better to shorten the original full code by less digits to get **_F5226J+9X_, Washington D.C.**

Something like this _could_ be part of the lookup table you suggest - basically a third column with just a boolean signalling whether the name is truly unique (shorten to 4+2 digits) or is used for more than one "tile" (shorten to 6+2 digits) - but I think that this is ignoring one of the main reasons why short plus codes exist.

The idea for them is to be easily communicated and understood. If I tell you that I can be found at "226J+9X Washington D.C.", it is easy for you to understand that you might want to first travel to Washington D.C., and then navigate to the exact address of "226J+9X" in that city.

If I am at the airport in Louisa, Virginia instead (which happens to be the second plus code I used in my previous example), I don't want to use "Washington D.C." as the name only because that is the biggest city in that "tile" - and you don't want to travel to Washington D.C. first, only to find out that I'm a two-hour drive away. ;)

Don't get me wrong: I agree that a compact file with useful name identifiers for offline use would be a great idea - I just don't think that this is how this should be achieved.

Last but not least, if we want to continue the discussion, it might better be done in a separate thread here, or perhaps in the discussion group at https://groups.google.com/forum/?pli=1#!forum/open-location-code
