### ISSUE TITLE
Multiple occupancy buildings

### ISSUE THREAD

**Issue by Chaz6** [google/open-location-code#141]
From reading the specification I could not work out how to identify for example flats that are vertically stacked within a high-rise multiple occupancy building.

**Comment by drinckes** [comment]
The quick response is that plus codes are aiming to be the street name and number (because the big problem is that most of the world doesn't have a street name).

Floor numbers, suite or apartment or flat numbers is something that has existing local conventions. We didn't think we needed to break those and if we included them into the code we'd lose the ability to have similar codes for nearby locations.

It's been suggested we should define a standard layout with the code and floor/suite number, say for addressing post - but there's organisations ([UPU](upu.int)) who already have standards for that ([S42](http://www.upu.int/en/activities/addressing/s42-standard.html)).

This question has been asked before - see #25 .
