### ISSUE TITLE
Relation to Google S2 coordinate scheme

### ISSUE THREAD

**Issue by mullender** [google/open-location-code#144]
What is the relation between plus code and the Google S2 coordinate scheme?
https://github.com/google/s2geometry

**Comment by drinckes** [comment]
None, other than both came out of Google :-) . S2 is nice for computers but there were two things we wanted to achieve with plus codes:

*  Not spell words. S2 cell IDs are made up of 0-9 and A-F, so they can spell words.
*  Nearby places should have similar references. Using S2 you can have neighbouring locations with very different codes. (This is also true of plus codes but it's not as common.)

We do like S2 - it's very good for data analysis, but we didn't think it was suitable as an addressing solution.

**Comment by mullender** [comment]
Thanks for the clarification, you could probably add your answer to the list of other systems:
https://github.com/google/open-location-code/wiki/Evaluation-of-Location-Encoding-Systems

**Comment by lokkju** [comment]
@drinckes Is there a reason you chose to use WSG84 lat/lon rather than S2 as your projection scheme? S2 has the advantage of not distorting nearly as much as a flat projection.

A couple quibbles with your answer so far:
1) S2 cell id's are not 0-9A-F, but rather bits represented as a long, that are often encoded as 0-9A-F; S2 cell id's could just as easily be encoded with your non-wordlike encoding scheme
2) Much the point of S2 was also to make nearby places have similar ID's; at least, it achieves that more successfully than geohash, for instance.

**Comment by drinckes** [comment]
An additional reason that fed into the decision was that the easiest way to obtain a location is using a GNSS device (smartphone). These provide locations in WGS84, so it makes sense to base any algorithm directly off that rather than introduce more layers of conversion.
