### ISSUE TITLE
Has anyone generated the grid(s) for use in GIS?

### ISSUE THREAD

**Issue by cumminsjp** [google/open-location-code#145]
Do the grids exist in the form of a  GIS dataset? shapefile, spatialite, geojson, etc.?

I would like to have a reference layer of the grids with my own data and was wondering if anyone  generated this and made it available publicly.

![image](https://user-images.githubusercontent.com/5941336/37593873-f2b2fce0-2b49-11e8-9fe2-42afc65aa82b.png)

**Comment by drinckes** [comment]
Hi, no, the grid doesn't exist as a shapefile, because at the fine levels it would be huuuuuge.

The easiest thing to do is to draw it for the area you want:

*  For a four digit grid, the lines are the degree latitude and longitude lines;
*  For a six digit grid, you have divide each degree into 20;
*  For an eight digit grid, you divide each degree into 400 (that is, each of the previous divisions is divided by 20);
*  For a 10 digit grid, you divide each degree into 8000 (that is, divide by 20 again).

Does that help?

**Comment by abdultanveer** [comment]
like to have a 10 digit grid overlaid on maps in which
1. repeated first 5 digits should be in small fonts and color coded
2. next 3 to be slightly bigger
3. next 2 big enough

**Comment by bgirardot** [comment]
@cumminsjp @drinckes has created a TMS server that will hopefully get hosted soon that sounds like it might meet your needs. I put some examples on twitter while I was testing it: https://twitter.com/BlakeGirardot/status/1036300493717467136

**Comment by answerquest** [comment]
precision level | intervals in lat-long units
-- | --
 10 | 0.000125
 8 | 0.0025
 6 | 0.05
 4 | 1
 2 | 20

We can generate the grid lines in [QGIS](https://www.qgis.org/).

Just make sure your starting lat-long values are an **exact multiple** of the interval values for your chosen precision level you want.  
example : Creating a grid with **precision 6** : starting latitude cannot be `16.4563`. Change it to `16.45` or `16.50` so that when you divide it by 0.05 it gives you an integer answer.

In QGIS, you can generate a grid by clicking in the top Menu: Vector > Research tools > Vector Grid

- Grid extent (xmin,xmax,ymin,ymax): `78.1,79,16.9,18.2` (in my example, a city in India)
- Set both lat and lon interval as per the precision level you want. So for precision level 6, enter `0.05` for both.
- You can set ourtput as lines or polygons, your choice. Lines make simpler and smaller shapefiles.
- And that should generate the grid for you. You can save that layer as a shapefile in any format. 

Note that this will not put any information about the pluscodes in your grid's metadata. They're just lines/boxes.

But if you make polygons, then I can think of a _roundabout_ way of adding pluscode values to those polygons (I have not done this myself yet):  
1. Generate a centroid layer (Vector > Geometry Tools > Polygon Centroid) from the grid-polygons layer. This will place points inside each grid box. (in a new points layer.)
2. Install "Lat Lon Tools" plugin.
3. That plugin can generate plus codes from points. So run it on the centroid layer you made.
4. (And this I can't quite figure out yet) Figure out a way to move the meta field from the centroid layer to the grid polygons layer.

QGIS does have python console etc so one could find a way to do this with some script, or make a plugin, or contribute to [Lat Lon tools](https://github.com/NationalSecurityAgency/qgis-latlontools-plugin). If someone finds a way, please post here!

**Comment by drinckes** [comment]
Hi Nikhil,

That's great information! I've put it into a wiki page on the github site
<https://github.com/google/open-location-code/wiki/Supporting-OLC-in-GIS>,
feel free to edit and add more if you like.

Ngā mihi,
Doug Rinckes, Technical Program Manager, Google Switzerland GmbH; 9G8F+6W Zü
rich <https://www.google.com/maps/search/9G8F%2B6W%20Z%C3%BCrich>

**Comment by drinckes** [comment]
In the meantime another option is to use the [grid service](https://grid.plus.codes)

This serves tiles that you can overlay into various maps and GIS platforms.

**Comment by fabanc** [comment]
@drinckes, @answerquest: I have also created a tool for the Esri community and ArcGIS Pro in order to compute plus code. You can compute the plus code directly on polygon that represent plus codes areas (in that case the plus code is based on the centroid of the polygon) or on points. You can define the length of the code you want as well.

This has been a problem I have been facing on a project and decided it would be a shame to not publish it. Since the datasets were big, computing the polygons centroid first and then joining was not an efficient option, so I have the tool the ability to compute the plus codes on the polygons as well.

The tool and a full tutorial on how to generate grids and plus code with the software in the ArcGIS / Esri world is on this GitHub project: https://github.com/fabanc/arcgis-plus-code-generator
