### ISSUE TITLE
Add Maven repository for devlopers 

### ISSUE THREAD

**Issue by pranimation** [google/open-location-code#152]
Please add maven repo of lib,This could help many android or cross platform developers.

**Comment by joshuaherman** [comment]
+1

**Comment by joshuaherman** [comment]
If you really want Curbmap can do the same for Maven as we did for Cocopods.

**Comment by zongweil** [comment]
@joshuaherman Thanks for the offer and for maintaining the Swift implementation. Since the Java implementation is part of this repo, I think it will make sense for us to include the Maven configuration here.

If you have some free time and want to set up the configuration and test it out, I'd be happy to review the pull request. Otherwise I'm hoping to get to this in the next few weeks.

**Comment by zongweil** [comment]
Maven config is there, next step is to add the library to Maven Central.

**Comment by zongweil** [comment]
Hey all,

Version 1.0 is now available in Maven Central. You can see the code here: https://oss.sonatype.org/content/groups/public/com/google/openlocationcode/openlocationcode/

Give it a try and let me know if including it via Maven Central is working for you! :)

**Comment by u201701** [comment]
wow, it actually worked in my android app; thank you @zongweil  :)

    implementation 'com.google.openlocationcode:openlocationcode:1.0.2'

**Comment by zongweil** [comment]
@u201701 Glad to hear!
