### ISSUE TITLE
Fixing Acadiana

### ISSUE THREAD

**Issue by LafayetteTravel** [google/open-location-code#160]
Hello, 

Acadiana is currently located in the incorrect place. 

862CCVWP+GX
(30.4463018,-91.1126054)

This brings you to an area located in the middle of Baton Rouge, when this is far from where this needs to be. 

Acadiana is a 22 Parish region of Louisiana, and Lafayette, Louisiana is considered the heart of it. 

https://en.wikipedia.org/wiki/Acadiana

https://en.m.wikipedia.org/wiki/Flag_of_Acadiana

The Acadian Flag was even designed by a professor at what is now the University of Louisiana at Lafayette. 

Please. Move this code to the correct latitude and longitude. 

(30.2427769,-92.0127186)

As well as defining this as an area. I’ve attempted to create a fusion table to fix this issue. 

https://fusiontables.google.com/DataSource?docid=1YbFImgZm9aFY3ou0Uk-KznVPK-xyRORke4rDFFK8#rows:id=1

If anything, please help correct that it is not Acadiana, Baton Rouge. 

If anything, it is Acadiana, Louisiana or Acadiana, Lafayette, Louisiana. 

Thank you.

**Comment by bocops** [comment]
This seems to be similar to an issue previously discussed on the mailing list: https://groups.google.com/forum/#!topic/open-location-code/40rTruLnAX8

Plus codes are not "assigned" to a locality, but are just a different representation of the already existing lat/long coordinates that Google Maps has for some location. If Google Maps returns the wrong coordinates when entering the search term "Acadiana", then that is a Maps issue that should be brought up via feedback from the Maps app (or, if you have, some other way of getting into contact with people responsible for the map data itself).

**Comment by zongweil** [comment]
Hi @LafayetteTravel,

As @bocops mentioned, this is an issue with what Google Maps is returning to us, which we unfortunately have no control over. From the thread on the mailing list, it sounds like you already have a contact within Google. If not, you can either submit the feedback via Google Maps or let me know and I can file a bug internally with the appropriate team.

I'm going to mark this issue as closed since it's not caused by anything on our end and we can't do anything directly about it.
