### ISSUE TITLE
Java implementation - why "final"?

### ISSUE THREAD

**Issue by bocops** [google/open-location-code#166]
Is there a reason for the OpenLocationCode class of the Java implementation being "final"? If not, can we remove that?

My reasoning is that, currently working on an app displaying plus codes to its users, it would be useful to create project-specific, additional functionality (like displaying a shortened code in some, but a full code in other, situations) using inheritance instead of having to wrap an OLC object in a separate class.

There are workarounds, of course, like creating my own fork to remove "final" - but I'd rather not go there unless really necessary.

**Comment by zongweil** [comment]
Great question! I originally added the final modifier, so I can answer.

The OpenLocationCode class is [immutable](http://thefinestartist.com/effective-java/15), meaning once it's instantiated, it can't be modified. You'll notice that the methods in the class return a new instance instead of modifying the existing one. This has benefits such as thread safety and being less error prone.

In order for a class to be truly immutable, the class should be marked with final so that subclasses can't modify internal state. Also, we wouldn't want to have someone use inheritance and depend on implementation details that may change in future versions.

Can you provide an example where inheritance makes it easier to work with the library over composition? For the situation you mentioned, what would your functionality look like in both cases? If there's enough of a case for it, I think it would be okay to remove final and be really careful with what internal data is exposed to subclasses.

**Comment by bocops** [comment]
@zongweil Thanks for the reply! Thread-safety makes sense, and is likely a bigger fish to fry than anything else - but for the sake of completeness:

The situation I mentioned (conditionally shortening a plus code) would definitely work with composition - in some other situations, though, I find myself copying private implementation details to make functionality work outside of the OLC class.

For example, a rather trivial (but fun!) use case is to suggest random locations nearby to users of a hyperlocal app. In combination with OLC, the way I'm currently doing it in one app is to
1. generate a daily location that satisfies certain conditions, based on a pseudo-random value that is the same for all users
2. generate an 8-digit plus code from that location's coordinates (essentially defining an area large enough to not immediately run into any huge privacy or safety concerns)
3. individualize plus code by adding two unique characters as suffix, to avoid sending all app users to the exact same spot
4. Display this plus code to users as a variant of "geohashing".

For (3), I find myself copying the definition of the private final String CODE_ALPHABET, a duplication which might lead to different problems down the line, should the internal definition change. I could of course work around that by individualizing the generated coordinates _before_ creating a plus code - but at that point, I would lose so many of the benefits of using OLC in the first place that I might as well drop its use completely (and I like using OLC ;)).

...turns out, just allowing inheritance wouldn't actually solve this problem unless some visibility modifiers get changed as well. Would making some of the definitions available to public be an option - either directly or via some sort of companion object. In that case, composition might work well enough. SEPARATOR and PADDING_CHARACTER might be other useful things to have access to.

**Comment by zongweil** [comment]
Thanks for the details! I don't see a problem with exposing those variables publicly. Feel free to send over a pull request :).

**Comment by zongweil** [comment]
Merged! Closing the issue.
