### ISSUE TITLE
Library jar not actually included on maven central

### ISSUE THREAD

**Issue by simonpoole** [google/open-location-code#186]
Currently only the pom.xml is present on maven central, wit https://search.maven.org/search?q=g:com.google.openlocationcode which is not particularly useful.

**Comment by zongweil** [comment]
Thanks for bringing this up! I'll look into this. Do you happen to know what needs to be changed to include the JAR? Is it a pom.xml configuration issue?

**Comment by kroka** [comment]
This issue might be caused by `<packaging>pom</packaging>` in https://github.com/google/open-location-code/blob/master/java/pom.xml#L14
I assume that the value should be `jar` instead.

* https://maven.apache.org/repository/guide-central-repository-upload.html
* https://central.sonatype.org/pages/requirements.html#correct-coordinates

**Comment by zongweil** [comment]
Thanks @kroka - that was the issue. MavenCentral shows the correct files now (https://search.maven.org/search?q=g:com.google.openlocationcode). Note that the version is now 1.0.0 instead of 1.0. We will go with that version scheme going forward.

**Comment by simonpoole** [comment]
Thanks @zongweil didn't have time to actually look at the issue.
