### ISSUE TITLE
Comparison with MGRS?

### ISSUE THREAD

**Issue by thw0rted** [google/open-location-code#224]
I read the whitepaper and was surprised not to see an entry for [MGRS](https://en.wikipedia.org/wiki/Military_Grid_Reference_System).  It's been a NATO standard for decades and is capable of expressing areas down to meter-square precision with 14 characters.  Codes are unique and only include 3 letters (not enough for a 4-letter word...), and the letters are always in the same place so there's no chance of confusing `O` for `0`.  The grid is not subject to license, has a long history, and there are existing libraries available for converting to and from lat/lon in many languages -- and they work offline.

The only criteria I think it violates is the classic grid problem, where there's no intuitive way to tell that boundary-adjacent refs (like 29SQE and 30STK) are close to each other, but I'd argue that no standard completely solves that problem.  And of course, there's no ability to use a shorter code + place name, or a shorter code interpreted as relative to your current location, but that also means you never need to provide a place-name lookup or other context to dereference a code.

Was MGRS considered during the study? Does it merit inclusion in the comparison?

**Comment by drinckes** [comment]
This question has been asked before
<https://groups.google.com/forum/#!topic/open-location-code/qJyxJ73jaYs>:

   - One point can have multiple MGRS codes (because the 100,000 meter
   squares necessarily overlap)
   - Nearby locations can have wildly different codes
   - And it's not much of an improvement over lat/lng, since there are
   still two numbers but now you have a bunch of letters as well.

Addresses are different to location references - because they need to be
understood by people. 40RCN 1234 5678 is a location reference. But "C44P+HV
Rough Rock, AZ, USA" is an address - you already know approximately where
it is just by reading it.

It all comes down to what was the problem you were trying to solve. MGRS
looks like was trying to make it easy to calculate distance and bearing
between two locations using just pencil and paper (so you could aim
artillery accurately - the M stands for Military). Actually providing
household addresses wasn't an objective. But that is exactly the aim of
plus codes.

Ngā mihi,
Doug Rinckes, Technical Program Manager, Google Switzerland GmbH; 9G8F+6W Zü
rich <https://www.google.com/maps/search/9G8F%2B6W%20Z%C3%BCrich>
