### ISSUE TITLE
Including floors in open location code

### ISSUE THREAD

**Issue by irvin** [google/open-location-code#25]
In large cities, when description a store, a restaurant or a venue, most of time we need to also state our it's floor. If we could also add floor number to the end of open location code, we can even present location where coordinate cannot cover.

We can considering to add a '+/-' in the end to indicate the floor numbers (ground floor = '+0', minus represent underground floor ).

**Comment by mprins** [comment]
`+` is already in use as a separator, eg. `22222222+22`

**Comment by irvin** [comment]
We can use second + for floors, eg., 7QQ32HM7+CV+77 represent Google in 77 floors of Taipei 101.

**Comment by drinckes** [comment]
We thought long and hard about floors or heights but decided against
including them in the base specification, mainly because we couldn't see
any major benefit beyond saying "7QQ32HM7+CV, Floor 77".

A floor number is helpful but doesn't actually give the exact destination.
I'm thinking of office buildings or hotels where you need a room or suite
number, possibly in addition to the floor.

It turns out that floors are counted differently in different countries -
the ground floor can be 0, or 1, or G, so we'd need to either choose one
(and confuse everyone everywhere) or say "we use the local idiom" and risk
that travelers get confused.

If you put it at the start or end, truncating the codes end up removing it,
and we wanted to be able to retain it.

The reason we couldn't see a strong benefit is that the phone can guide you
to 7QQ32HM7+CV, through the use of location and GPS services, but it can't
guide you to the 77th floor, because it doesn't know how high up that is.
The floor number is something you need to know, so that you can press the
right lift button, so putting it into an opaque string cold be seen as
reducing it's usefulness.

Does that help?


Doug Rinckes
Technical Program Manager
Google Switzerland

**Comment by irvin** [comment]
Enough to understood. However as your example, people still need to know the floor numbers when we locate some place, so a floor numbers must come with the code in metropolitan. In this situation, it's always better to decide a specific format that machine can read and process, which floor 77 / 77F / 77 階 / 77 樓 / G / T / R... or it's many various represent methods across different language and culture are hardly to recognize by machine and obviously not good enough.

Looking forward to see this into next version of spec.

**Comment by karussell** [comment]
I would love to have the 3rd dimension included as e.g. altitude but not separately instead directly encoded and e.g. noted that the code is 3 or 2 dimensional. This way the application could theoretically convert it into a local floor definition but at least the smartphone could guide you to the correct height e.g. guided by local installed WLAN indoor systems giving precise height informations.

> I'm thinking of office buildings or hotels where you need a room or suite number, possibly in addition to the floor.

If you have the location you have the room already or did I misunderstand this part?

**Comment by ben221199** [comment]
If you go with altitude, I was thinking about `@`, because you are "AT some height". A Plus Code would be something like this: `9C3W9QCJ+2VX@100` to say you are at 100 meters high. (But I can imagine that other symbols can be choosen too; as long as it isn't `#`, `?`, `/` or `\`, because you probably want codes to be used in HTTP URLs).

I think that it is possible to add some altitude-like thing to the OLC spec, as long as it is mentioned that it is a suffixed thing and not part of the core string. That should mean that the suffix stays when recovering or shortening: `+2VX@100`.

Also, what sign should be used when doing extraterrestrial stuff: https://github.com/google/open-location-code/issues/499?

**Comment by ofou** [comment]
> If you go with altitude, I was thinking about `@`, because you are "AT some height". A Plus Code would be something like this: `9C3W9QCJ+2VX@100` to say you are at 100 meters high. (But I can imagine that other symbols can be choosen too; as long as it isn't `#`, `?`, `/` or `\`, because you probably want codes to be used in HTTP URLs).
> 
> I think that it is possible to add some altitude-like thing to the OLC spec, as long as it is mentioned that it is a suffixed thing and not part of the core string. That should mean that the suffix stays when recovering or shortening: `+2VX@100`.
> 
> Also, what sign should be used when doing extraterrestrial stuff: #499?

I think this is a very good idea, but I'd rather go with altitude (orthometric height) instead of floors which is imprecise, plus most of systems already use meters as metric.
