### ISSUE TITLE
Google Maps shows the wrong locality in the plus code address

### ISSUE THREAD

**Issue by ANDRELOGIN** [google/open-location-code#251]

**Comment by ANDRELOGIN** [comment]
I changed my address on google maps but the plus code doesnot change whit. 
How can i change de plus code?

**Comment by zongweil** [comment]
The plus code is attached to a specific area. On Google Maps, the area is roughly 13mx13m. If your new address is within that same area as the old one, it will still have the same plus code.

If this is not the case (your new address is far away from the old one), could you describe more what you mean? Are you talking about the plus code in the left panel of Google Maps?

**Comment by ANDRELOGIN** [comment]
here:
https://www.google.com/maps/place/Rocha+Engenharia/@-27.0996503,-48.9226397,18.75z/data=!4m5!3m4!1s0x0:0x689338c56f1ceec4!8m2!3d-27.0999247!4d-48.922615?hl=pt-BR

the correct is: "Centro 1, Brusque-sc, and not "Aymoré, Guabiruba-sc"
Can you help please?

**Comment by ANDRELOGIN** [comment]
"Are you talking about the plus code in the left panel of Google Maps?"
yes.

**Comment by zongweil** [comment]
Thanks for clarifying. How did you change your address? Was it through Google My Business?

**Comment by ANDRELOGIN** [comment]
You're wellcome, yes I change through GMB. Thanks for helping.

**Comment by drinckes** [comment]
At the moment, the locality used in the plus code does not come from the address, but from the best guess for that location (given the plus code constraints). This is because some localities are too large, and some are so small and obscure that they aren't well known.

(Remember that ""W32G+2X Aimoré, Guabiruba" means the nearest W32G+2X to Aimoré, Guabiruba. It doesn't have to be *within* it, just near it.)

In your case, you moved your business. The plus code changed, but because it was a short distance, the locality in the plus code address doesn't update right away. It will be recomputed in a couple of days, and then the plus code address will be "W32G+2X Brusque, SC, Brasil" (like all the neighbouring businesses). In the meantime **it still works** - it **will** get someone to your new location.

All of that said, this is something we're looking at and planning to address (if you'll forgive the pun) by reusing the locality from your street address where possible.

(I've edited the issue title slightly to reflect the problem.)
