### ISSUE TITLE
Ajax request returning cors error

### ISSUE THREAD

**Issue by LarBearrr** [google/open-location-code#252]
I'm having similar issues as #151 however, the posted solution is not working. 

I'd like to make a call to the API using AJAX if possible so I can return the global code for an address I will be using in a request to my backend. Here's my code:
```
    function getGlobalCode() {
        var place = autocomplete.getPlace();

        let place_address = encodeURIComponent(place.formatted_address);

        let apiKey = 'myApiKey'

        var queryString = "address="+place_address+"&key="+apiKey

        var apicall = 'https://plus.codes/api?address=' + place_address + '&ekey=' + apiKey;

        $.get({
            url: apicall,
            success: function(data) {
                console.log(data); 
            }
        });
    }
```
currently returning `blocked by CORS policy: Request header field x-csrf-token is not allowed by Access-Control-Allow-Headers in preflight response.`

Any suggestions or advice appreciated. Thank you.

**Comment by drinckes** [comment]
Hi @LarBearrr, I think this is because your framework is including a `X-CSRF-Token` header in the request, and then the plus codes API doesn't declare itself as supporting this header, because it's not vulnerable to CSRF attacks (there's no authentication or state).

I assume you're using jQuery? Check your code for something that adds that header to the jQuery config - it might look something like:
```
$.ajaxSetup({ headers: { 'X-CSRF-Token': ... } });
```
and see if you can remove it.

**Comment by LarBearrr** [comment]
@drinckes You are correct. I believe I solved this by deleting the header from ajaxSetup in this specific method before the request is made. My apologies for leaving this issue open and thank you for the reply!

**Comment by drinckes** [comment]
Awesome!
