### ISSUE TITLE
[olc_definition.adoc] "Code areas distort at high latitudes" - need more explanation

### ISSUE THREAD

**Issue by 365ejk** [google/open-location-code#255]
"Code areas distort at high latitudes due to longitude convergence."

Is it solely due to "longitude convergence" ? 
Is it also in such a way because plus codes method tries to cover as many latitudes as possible since north/south pole area is not much populated ?

Is it possible to add more explanation?

**Comment by bocops** [comment]
No, it is solely due to convergence. OLC is basically just a repeated division of the existing lat/long grid - 20°, 1°, 0.05° etc. Longitudinal lines converge towards the equator, so the area defined by two of those lines gets distorted towards the poles.

This actually means that a plus code of any given length is more precise near the poles, not less. If population of an area was taken into account, the opposite would probably have been attempted.
