### ISSUE TITLE
What problem is this trying to solve?

### ISSUE THREAD

**Issue by lazarillo** [google/open-location-code#271]
I don't mean for this title/header to come off as combative. I just ran across this concept of plus codes in its non-programming context (via the [plus codes home page](https://plus.codes/)).

As a programmer, this makes sense to me. We are all used to new paradigms, methodologies, and technologies popping up all the time.

But it seems to me that `open-location` is trying to get this to be a success with the larger public.  Is that correct?

If so, it seems its success is as likely as that of the language [Esperanto](https://en.wikipedia.org/wiki/Esperanto).  Some things in the real world are simply ingrained and understood, regardless of their efficiency.  Is `open-location` / plus-codes useful outside of the tech world?  How do folks imagine it being used?  If it is only useful for coding / technology, how is it expected to be used?

I like the idea... it just seems doomed to me, so I'm hoping I'm missing something.

----

I apologize for submitting this question as an "issue", but there was no mention in the documentation as to how / why the technology should be used.

**Comment by zongweil** [comment]
@drinckes in case he has anything to add

Hello!

Thanks for the question and for explaining where you're coming from. You are correct in that plus codes are intended for general public usage. The website actually explains a lot of the benefits:

"A plus code is like a street address for people or places that don't have one.

Plus codes give addresses to everyone, everywhere, allowing them to receive deliveries, access emergency services, register to vote, and are already improving peoples' lives."

More on the "Benefits" tab.

> Some things in the real world are simply ingrained and understood, regardless of their efficiency.

I'm not sure what "things" you're referring to here, but plus codes are essentially solving the usability issues of latitude/longitude. A lot of the world doesn't have street addresses, which makes a lot of tasks really difficult (like delivering mail). You could directly use lat/long, but try getting someone to memorize it.

Plus codes are already used on a large scale in real life. We worked with [Addressing the Unaddressed](https://www.addressingtheunaddressed.org/) to [map out slums in Kolkata](https://www.youtube.com/watch?v=Hd3gGspgVGs). The country of Cape Verde used plus codes to [deliver in-home mail](http://www.correios.cv/conteudo.aspx?id=1843&cid=1844) _for the first time_.

The goal of plus codes was always to solve real-world problems due to lack of street addressing. Let me know if you have any other questions on its usage - happy to elaborate!

**Comment by drinckes** [comment]
Hi @lazarillo - it's amazing the places where there are no street addresses, and the problems this causes.

Even within the US you have large rural areas without addresses, and this causes all kinds of problems, including management of voter registrations and boundary changes, deliveries, emergency service responses. In other countries lack of addresses fuels tax fraud and evasion, reducing the ability of governments to develop their economies.

Here's a another video [illustrating the issue in rural US](https://www.youtube.com/watch?v=JwlGL_oC0SI&t=4s).

**Comment by lazarillo** [comment]
@drinckes @zongweil Thanks for your responses! I guess I had trouble imagining that there are places so poor and/or secluded that they do not have addresses, yet so technologically savvy that they would adopt this very novel means of providing a location.  Sounds like I lack imagination.  😏

**Comment by fiveham** [comment]
@lazarillo Here's another potential use-case for this concept:

Last year a change was made to North Dakota elections laws to require that a voter's address be included on their ID for them to be eligible to vote. [Native Americans living on a reservation were disproportionately impacted by this change](https://www.npr.org/2018/10/13/657125819/many-native-ids-wont-be-accepted-at-north-dakota-polling-places) since the largely European-originated concept of a street address wasn't something that their tribal IDs accounted for.

I don't suppose that state and tribal governments would be especially likely to start accepting or using plus codes as substitutes for classic street addresses on IDs, but they couldn't exactly start doing that anyway if plus codes didn't exist yet.
