### ISSUE TITLE
Incorrect City Causing Mail Reroute

### ISSUE THREAD

**Issue by Monica6128** [google/open-location-code#354]
2 Buena Vista Terrace, Central Valley, NY 10917
8VCF+77 Woodbury, NY

The plus code is pointing to the wrong city name, which is causing applications that use this coding to reroute mail to an entirely different part of the state.

**Comment by drinckes** [comment]
Hi @Monica6128 
Google Maps tries to use place names that are a bit larger than central valley, since they may not be well known in all of the world. That said, if you are telling someone your address, you could say 8VCF+77 Central Valley, NY and that should also work.

Are you using this for regular USPS mail?
