### ISSUE TITLE
GCJ-02 coordinates

### ISSUE THREAD

**Issue by eddydas** [google/open-location-code#359]
Do you have plans to adapt/augment the system to handle cases where WSG-84 is not permitted in the local jurisdiction, such as China (which uses GCJ-02 coordinates)?

Reference: https://en.wikipedia.org/wiki/Restrictions_on_geographic_data_in_China#Coordinate_systems

**Comment by drinckes** [comment]
No, no plans.

As long as the input values are between -90 to 90 and -180 to 180, then you could use any coordinate system - as long as it is agreed between whoever is encoding the location and whoever is decoding the location.

But our recommendation is that a plus code should be based on WGS-84, since it is vastly more likely that any system you use a plus code with is going to assume the decoded values are WGS-84.
