### ISSUE TITLE
Pluse code and designing an app for  customer 

### ISSUE THREAD

**Issue by HazemMuhsen** [google/open-location-code#465]
HI guys 
I'm not developer  but I found a problem and I try to find a solution 
in my country I have no  regular addressing and as the ecommerce nowadays is big  theres a hundred of  delivering company for delevering products as well as food and the way that they working is depends onphone call and description the  address till the driver reach the destination and it is  slow and not the appropriate  way  with the existing of technology so 

I have some points and could you please help me out in answering me  and suggest me as well  the perfect way to do it 

1- the  google pluse code is an open source and it is free and i can used the codes online and offline 
2- can i do an app on ios and android for making each person automatically show his address  in offline mode as well as online 
3-any one have made like this application in any country 
4- can I change part of  google plus code  to names

thanks in advanced for every one

**Comment by bilst** [comment]
Hi HazemMuhsen, thanks for your interest! Delivery in a region without
street addresses sounds like a good use case for plus codes.


Plus codes have open source libraries in many languages, so anyone can
build an app using them or add them to their ecommerce app. They're also
available online and offline in Google Maps, which is widely available.
Here's a guide to using them in Google Maps:
https://support.google.com/maps/answer/7047426?co=GENIE.Platform%3DAndroid&oco=1


For #4, compound plus codes (e.g. "*MP92+W5* Tokyo" instead of "8Q7X
*MP92+W5*"), apps integrating plus codes need to know where Tokyo is. For
delivery apps servicing a particular region they may have a list of
city/town/village names to use, or can use a geocoding API to determine
place name locations. Google provides one for a pretty low cost:
https://developers.google.com/maps/documentation/geocoding/overview

Or the Nominatim API (based on Open Street Maps) is a free alternative:
https://wiki.openstreetmap.org/wiki/Nominatim


Cheers, Bill

**Comment by bocops** [comment]
Hi @HazemMuhsen

This place is mostly used to discuss problems with the actual code used to generate plus codes. If you are interested in a conversation about the use of plus codes, it would be better to use the group here instead: [Google group](https://groups.google.com/g/open-location-code). I'm watching that group as well, so if you have further questions I can answer them there.

That said, let me try to just answer your immediate questions right now, before this issue will be closed later:

1. Yes, the algorithm to create and decipher plus codes is public and can be used by anyone free of charge. To be precise, everything is licensed under the [Apache-2.0 license](https://github.com/google/open-location-code/blob/main/LICENSE), which is considered to be a "free" license.
2. Yes. Because the algorithm is "free", you could take one of the implementations published on this page, or write your own, to create an app that turns GPS coordinates into plus codes and the other way around. There's a slight difference between "short" codes which only work online, and "full" codes which should work offline.
3. Searching for "plus code" on Google Play leads to some results, although I can't say if any of the results is an app that works well. For what it's worth, Google Maps shows your plus code if you tap the blue dot on the map. This seems to work even if I put my device into airplane mode, so this might be sufficient already.
4. Something like that is the difference between "full" and "short" codes. A full code typically consists of ten or eleven characters separated by a plus character like this: **6789CFGH+XX**. The first four characters are sometimes replaced by the name of a nearby city, like this: **CFGH+XX Corococha**. If this is done, the resulting code is considered to be a "short" one, and it will probably be necessary for the receiver to be online to properly decode the coordinates.

**Comment by HazemMuhsen** [comment]
Thanks For both of you.Cheers, Bill  and Andreas bocops

I will take your advice and looking in that  deeply 
and I still looking for some one in any country how have  best practice in that  and have been done an app for the same issue

Regards 
Hazem
