### ISSUE TITLE
Add DMS units to table. Not only just fractional degrees

### ISSUE THREAD

**Issue by jidanni** [google/open-location-code#577]
https://github.com/google/open-location-code/blob/main/docs/specification.md#code-precision has "Precision in degrees" as a table column.

There should also be an additional column to its right, stating the minutes / seconds equivalent.

For instance, 1/20 of a degree is also simply three (arc) minutes.

**Comment by drinckes** [comment]
I'm not sure why this would be useful since the table already includes the meter dimensions (that I think is much more understandable). At 10 digits the precision is 0.45 seconds and I'm not sure how many people have an idea of what that means.

I mean if you want to include the table with the values here as a comment we can see what it looks like and if anyone feels it is useful.

**Comment by drinckes** [comment]
I'm going to take it that since no table has appeared this isn't a priority, so I'll close the issue.
