### ISSUE TITLE
Creating or using pluse.codes website is not possible offline since Nov'16 update

### ISSUE THREAD

**Issue by morciej** [google/open-location-code#58]
With initial version of http://plus.codes demo site, it was possible to find out the plus code of one's own location, and find distance to a location given as a plus code. After the update, it is no longer possible. The site needs to be downloaded to use any functionality at all.

**Comment by drinckes** [comment]
True - however I'm closing the issue here because it's not a problem with the Open Location Code library itself. (It'd be better over [here](https://github.com/drinckes/pluscodes) but read below first.)

To use the codes offline, you can use Google Maps on your device. Google Maps supports offline areas that you can download, and then the maps, search and navigation work offline. (https://support.google.com/maps/answer/6291838)

Searching for plus codes while offline is supported. To discover a code, long press on the map and pull up the card. (https://support.google.com/maps/answer/7047426)

In addition, I'm hopeful that we can get other map providers and apps to support the codes both online and offline (e.g. Maps.Me). You can help by raising issues or support tickets so that they know there is a desire for this feature.

Thanks for your comment! I'll look into whether we can do something with the website, although it isn't going to be quick. HTML5 caching isn't trivial to get to work reliably. :-(
