### ISSUE TITLE
Code translation (other coding language)

### ISSUE THREAD

**Issue by ghost** [google/open-location-code#65]
Do you have a TCL version? If not, I have "translated" the code and the test suite passes successfully (VBA --> TCL)

Sorry for the bug report; I couldn't find a "contact" link for this project.

**Comment by drinckes** [comment]
Hi, that's very cool! If you create your own GitHub repo, we'd love to link to it. That's probably best, since I'm sure you know TCL better than me. :-)

Would that be ok?

**Comment by maimizuno** [comment]
Sadly, my knowledge of GitHub and things like repos and forks are kinda over my head. I don't believe I would properly manage it.

**Comment by maimizuno** [comment]
Upgraded to include sanity checks (enhancement to test suite). Some of these should be made available to the other versions (languages).

[OLC:test] All test successfully passed.

OLC encode: (+000.0000000,+000.0000000) --> 6FG22222+22
OLC encode: (-090.0000000,-180.0000000) --> 22222222+22
OLC encode: (-090.0000000,+180.0000000) --> 22222222+22
OLC encode: (+090.0000000,-180.0000000) --> C2X2X2X2+X2
OLC encode: (+090.0000000,+180.0000000) --> C2X2X2X2+X2
OLC encode: (-045.0000000,-045.0000000) --> 487Q2222+22
OLC encode: (-045.0000000,+045.0000000) --> 4H772222+22
OLC encode: (+045.0000000,-045.0000000) --> 88QQ2222+22
OLC encode: (+045.0000000,+045.0000000) --> 8HQ72222+22
OLC encode: (+033.8121010,-117.9189530) --> 8554R36J+RC
OLC encode: (+033.8121010,-117.9189530@11) --> 8554R36J+RCV
OLC encode: (+033.8121010,-117.9189530@12) --> 8554R36J+RCV4
OLC encode: (+033.8121010,-117.9189530@13) --> 8554R36J+RCV46
OLC encode: (+033.8120920,-117.9189640@15) --> 8554R36J+RCMJG34

OLC decode: 8554R36J+RC --> (+033.8120000,-117.9190000) to (+033.8121250,-117.9188750)
OLC decode: 8554R36J+RCV --> (+033.8121000,-117.9189688) to (+033.8121250,-117.9189375)
OLC decode: 8554R36J+RCV4 --> (+033.8121000,-117.9189531) to (+033.8121050,-117.9189453)
OLC decode: 8554R36J+RCV46 --> (+033.8121010,-117.9189531) to (+033.8121020,-117.9189512)
OLC decode: 8554R36J+RCMJG34 --> (+033.8120920,-117.9189641) to (+033.8120920,-117.9189640)

OLC offset: (33.812101,-117.918953):
        +033.8120000 to +033.8121250 (-000.0001010 to +000.0000240)
        -117.9190000 to -117.9188750 (-000.0000470 to +000.0000780)
OLC offset: (33.812101,-117.918953):
        +033.8121000 to +033.8121250 (-000.0000010 to +000.0000240)
        -117.9189688 to -117.9189375 (-000.0000158 to +000.0000155)
OLC offset: (33.812101,-117.918953):
        +033.8121000 to +033.8121050 (-000.0000010 to +000.0000040)
        -117.9189531 to -117.9189453 (-000.0000001 to +000.0000077)
OLC offset: (33.812101,-117.918953):
        +033.8121010 to +033.8121020 (-000.0000000 to +000.0000010)
        -117.9189531 to -117.9189512 (-000.0000001 to +000.0000018)
OLC offset: (33.812092,-117.918964):
        +033.8120920 to +033.8120920 (-000.0000000 to +000.0000000)
        -117.9189641 to -117.9189640 (-000.0000001 to +000.0000000)

OLC verify (code): 33.812101 -117.918953 matches 8554R36J+RC
OLC verify (code): 33.812101 -117.918953 11 matches 8554R36J+RCV
OLC verify (code): 33.812101 -117.918953 12 matches 8554R36J+RCV4
OLC verify (code): 33.812101 -117.918953 13 matches 8554R36J+RCV46
OLC verify (code): 33.812092 -117.918964 15 matches 8554R36J+RCMJG34

OLC verify (coordinates): 8554R36J+RC properly encompasses (33.812101,-117.918953)
OLC verify (coordinates): 8554R36J+RCV properly encompasses (33.812101,-117.918953)@11
OLC verify (coordinates): 8554R36J+RCV4 properly encompasses (33.812101,-117.918953)@12
OLC verify (coordinates): 8554R36J+RCV46 properly encompasses (33.812101,-117.918953)@13
OLC verify (coordinates): 8554R36J+RCMJG34 properly encompasses (33.812092,-117.918964)@15

Intentional errors:

OLC verify (code): mismatch: 33.812101 -117.918953
        expected 8554R36J+RC (got 8554R36J+RG)

OLC verify (coordinates): 8554R36J+RG does not encompass (33.812101,-117.918953):
        Lng (-117.918953) < LngLo (-117.91875)

OLC verify (code): mismatch: 33.812092 -117.918964 15
        expected 8554R36J+RCMJG34 (got 8554R36J+RCMJG35)

OLC verify (coordinates): 8554R36J+RCMJG35 does not encompass (33.812092,-117.918964):
        Lng (-117.918964) < LngLo (-117.91896398925782)

<end of tests>

**Comment by maimizuno** [comment]
Just touching base.... Since I have no knowledge of how to do git repositories, if you were willing to walk me through it, I could try. Otherwise, I'd prefer to just hand it to you (with proper credit/attribution) for uploading to your project. See me online (IRC; email me for the address) or comment here.

**Comment by maimizuno** [comment]
We're writing to let you know that the group you tried to contact (pluscodes) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:

 * You might have spelled or formatted the group name incorrectly.
 * The owner of the group may have removed this group.
 * You may need to join the group before receiving permission to post.

**Comment by zongweil** [comment]
Just updated the permissions. Can you try again?

**Comment by maimizuno** [comment]
I will, but, I'm curious what needs to be 'worked out' privately?

I wrote the code, it's tested, and I'm offering it.
I do not know enough about GIT {nor care, to be honest] to create some spin-off repository to post it.
It's not my creation anyway; it's yours. I simply translated it into another language [and did some tweaking and bug-fixing (already reported)].
Either it's beneficial and I can post it, or, it's not (and I'll go away).

Simplicity seems to have been lost thanks to technology (mainly social media).

*Has headache, lying down*

**Comment by zongweil** [comment]
Sorry that this feels so complex. I was planning to walk you through how to use Git over email, but it sounds like that approach is out of the question now.

The normal way you integrate new code into a Github repo is to create a fork of the main repo, make changes to your copy of the repo, then send a pull request with the changes back to the main repo. That's what it means to "post it" in the Github world.

Since you'd like to avoid that effort, just include a zip of your code in a comment or email. We'll review it in the next few weeks and add it to the main repo with attribution to your Github username. Does that sound reasonable?

Hope your headache goes away soon!

**Comment by maimizuno** [comment]
[openlocation-tcl.zip](https://github.com/google/open-location-code/files/2021557/openlocation-tcl.zip)
